# Generated by Django 3.0.6 on 2020-06-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('x_dim', models.IntegerField(blank=True, null=True)),
                ('y_dim', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imark.Img')),
            ],
        ),
        migrations.AddField(
            model_name='img',
            name='notes',
            field=models.ManyToManyField(related_name='image_notes', to='imark.Note'),
        ),
    ]
