# Generated by Django 3.0.6 on 2020-06-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imark', '0003_auto_20200602_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Title', max_length=250),
        ),
    ]
