# Generated by Django 3.0.6 on 2020-06-04 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imark', '0004_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='set_author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
